name: firebase_database_mock

description: Mocks to write unit tests for FirebaseDatabase (real-time database).

version: 0.1.0

repository: https://github.com/matheuskildere/flutter_firebase_database_mock.git
homepage: https://github.com/matheuskildere/flutter_firebase_database_mock.git
issue_tracker: https://github.com/matheuskildere/flutter_firebase_database_mock/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^7.2.0
  pedantic: ^1.9.2
  mockito: ^5.0.14
  firebase_core_platform_interface: ^4.0.1
  flutter_test:
    sdk: flutter
